[package]
name = "damms"
version = "0.1.1"
edition = "2021"


[dependencies]
ethers = { version = "2.0.1", default-features = false, features = ["abigen", "ipc", "rustls"] }
tokio = { version = "1.21.0", features = ["full"] }
futures = "0.3.24"
indicatif = "0.17.1"
thiserror = "1.0.36"
async-trait = "0.1.57"
serde_json = "1.0.85"
serde = "1.0.145"
num-bigfloat = "1.6.2"
uniswap_v3_math = "0.2.26"
regex = "1.7.1"

